const ERROR_CODES = {
    // Auth
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',

    // User
    USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
    USER_LOCKED: 'USER_LOCKED',
    USER_INACTIVE: 'USER_INACTIVE',

    // Common
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
};

export default ERROR_CODES;
