export enum SOCKET_NOTIFICATION_ACTIONS {
    ADD_NOTIFICATION = 'ADD_NOTIFICATION',
    MARK_AS_READ = 'MARK_AS_READ',
    DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
    CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS',
}
