export enum SOCKET_NOTIFICATION_ACTIONS {
    SET_NOTIFICATIONS = 'SET_NOTIFICATIONS',
    ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION',
    MARK_AS_READ = 'MARK_AS_READ',
    DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
    CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS',
}
