export enum SOCKET_NOTIFICATION_ACTIONS {
    SET_NOTIFICATIONS = 'SET_NOTIFICATIONS',
    ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION',
    DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
    CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS',
    MARK_ALL_AS_READ = 'MARK_ALL_AS_READ',
}
