export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_PENDING_MESSAGE = 'ADD_PENDING_MESSAGE';
export const REPLACE_MESSAGE = 'REPLACE_MESSAGE';
export const ADD_INCOMING_MESSAGE = 'ADD_INCOMING_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
