const fakeUserDB = [
    {
        id: 1,
        username: 'dat123',
        name: 'Nguyễn Văn Đạt',
        email: 'dat@example.com',
        password: '123456',
        avatar_link: 'https://i.pravatar.cc/150?img=1',
    },
    {
        id: 2,
        username: 'linh456',
        name: 'Trần Thị Linh',
        email: 'linh@example.com',
        password: 'abcdef',
        avatar_link: 'https://i.pravatar.cc/150?img=2',
    },
    {
        id: 3,
        username: 'hoa789',
        name: 'Phạm Thị Hoa',
        email: 'hoa@example.com',
        password: 'qwerty',
        avatar_link: 'https://i.pravatar.cc/150?img=3',
    },
    {
        id: 4,
        username: 'nam321',
        name: 'Lê Văn Nam',
        email: 'nam@example.com',
        password: 'pass123',
        avatar_link: 'https://i.pravatar.cc/150?img=4',
    },
    {
        id: 5,
        username: 'mai654',
        name: 'Đỗ Thị Mai',
        email: 'mai@example.com',
        password: 'hello123',
        avatar_link: 'https://i.pravatar.cc/150?img=5',
    },
    {
        id: 6,
        username: 'hoang987',
        name: 'Vũ Minh Hoàng',
        email: 'hoang@example.com',
        password: 'mypassword',
        avatar_link: 'https://i.pravatar.cc/150?img=6',
    },
    {
        id: 7,
        username: 'anh001',
        name: 'Nguyễn Thị Ánh',
        email: 'anh@example.com',
        password: 'abc12345',
        avatar_link: 'https://i.pravatar.cc/150?img=7',
    },
    {
        id: 8,
        username: 'thuy002',
        name: 'Bùi Thùy Linh',
        email: 'thuy@example.com',
        password: 'password!',
        avatar_link: 'https://i.pravatar.cc/150?img=8',
    },
    {
        id: 9,
        username: 'trung003',
        name: 'Phan Văn Trung',
        email: 'trung@example.com',
        password: '123abc456',
        avatar_link: 'https://i.pravatar.cc/150?img=9',
    },
    {
        id: 10,
        username: 'huyen004',
        name: 'Lý Thị Huyền',
        email: 'huyen@example.com',
        password: 'letmein',
        avatar_link: 'https://i.pravatar.cc/150?img=10',
    },
    {
        id: 11,
        username: 'minh005',
        name: 'Ngô Minh Đức',
        email: 'minh@example.com',
        password: 'minhpass',
        avatar_link: 'https://i.pravatar.cc/150?img=11',
    },
    {
        id: 12,
        username: 'thu006',
        name: 'Trần Thu Hà',
        email: 'thu@example.com',
        password: 'hathutrang',
        avatar_link: 'https://i.pravatar.cc/150?img=12',
    },
    {
        id: 13,
        username: 'long007',
        name: 'Đặng Trường Long',
        email: 'long@example.com',
        password: 'longdragon',
        avatar_link: 'https://i.pravatar.cc/150?img=13',
    },
    {
        id: 14,
        username: 'khanh008',
        name: 'Vũ Khánh Linh',
        email: 'khanh@example.com',
        password: 'linhkhanh',
        avatar_link: 'https://i.pravatar.cc/150?img=14',
    },
    {
        id: 15,
        username: 'tam009',
        name: 'Nguyễn Thành Tâm',
        email: 'tam@example.com',
        password: 'tam123456',
        avatar_link: 'https://i.pravatar.cc/150?img=15',
    },
    {
        id: 16,
        username: 'yen010',
        name: 'Hoàng Thị Yến',
        email: 'yen@example.com',
        password: 'yenyen123',
        avatar_link: 'https://i.pravatar.cc/150?img=16',
    },
    {
        id: 17,
        username: 'bao011',
        name: 'Phan Bảo Ngọc',
        email: 'bao@example.com',
        password: 'baongoc1',
        avatar_link: 'https://i.pravatar.cc/150?img=17',
    },
    {
        id: 18,
        username: 'son012',
        name: 'Lê Nhật Sơn',
        email: 'son@example.com',
        password: 'sonle123',
        avatar_link: 'https://i.pravatar.cc/150?img=18',
    },
    {
        id: 19,
        username: 'quynh013',
        name: 'Đào Quỳnh Anh',
        email: 'quynh@example.com',
        password: 'quynhanh',
        avatar_link: 'https://i.pravatar.cc/150?img=19',
    },
    {
        id: 20,
        username: 'tung014',
        name: 'Trần Anh Tùng',
        email: 'tung@example.com',
        password: 'tunganht',
        avatar_link: 'https://i.pravatar.cc/150?img=20',
    },
];

export default fakeUserDB;
