export enum MessageCacheActionType {
    SET_MESSAGES = 'SET_MESSAGES',
    ADD_PENDING_MESSAGE = 'ADD_PENDING_MESSAGE',
    REPLACE_MESSAGE = 'REPLACE_MESSAGE',
    ADD_INCOMING_MESSAGE = 'ADD_INCOMING_MESSAGE',
    DELETE_MESSAGE = 'DELETE_MESSAGE',
}
