// src/constants/socketTypes.js
export enum SOCKET_EVENTS {
    REALTIME_EVENT = 'realtime-event',
    SET_SOCKET = 'SET_SOCKET',
}

export enum SOCKET_PAYLOAD_TYPES {
    MESSAGE = 'MESSAGE',
    TYPING = 'TYPING',
    COMMENT = 'COMMENT',
    GROUP_UPDATE = 'GROUP_UPDATE',
    NOTIFICATION = 'NOTIFICATION',
    STOP_TYPING = 'STOP_TYPING',
    READ_RECEIPT = 'READ_RECEIPT',
    SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION',
}
